### ISSUE TITLE
rerun does not work naively in c9.io/sinatra?

### ISSUE THREAD

**Issue by LianaSaussy** [ZachBeta/ruby-newbie#5]
Upon change of file, rerun attempts to restart program as normal. However, launch fails and the error message "Someone is already performing on port 8080!" is returned.

I tried adding the flag -signal KILL to force the process to terminate faster. I found that the PID returned by lsof -wni in the terminal did not match the ID of the process rerun attempted to terminate when using -signal KILL:

Example:

terminal window 1
```
username@ruby-newbie:~/workspace/sinatra_with_reload (master) $ rerun --signal KILL 'ruby hello_world.rb -p $PORT -o $IP'

23:28:17 [rerun] Sinatra_with_reload launched
[2015-03-26 23:28:18] INFO  WEBrick 1.3.1
[2015-03-26 23:28:18] INFO  ruby 2.1.5 (2014-11-13) [x86_64-linux]
== Sinatra/1.4.2 has taken the stage on 8080 for development with backup from WEBrick
[2015-03-26 23:28:18] INFO  WEBrick::HTTPServer#start: pid=14569 port=8080
[Listen warning]:
  Missing dependency 'rb-inotify' (version '~> 0.9')!
  Please add the following to your Gemfile to satisfy the dependency:
    gem 'rb-inotify', '~> 0.9'
  
  For a better performance, it's recommended that you satisfy the missing dependency.
  Listen will be polling changes. Learn more at https://github.com/guard/listen#polling-fallback.
23:28:19 [rerun] Watching ["."]/**/*.{rb,js,css,scss,sass,erb,html,haml,ru} using Polling adapter
23:28:22 [rerun] Change detected: 1 modified
23:28:22 [rerun] Sending signal KILL to 14564

23:28:22 [rerun] Sinatra_with_reload restarted
[2015-03-26 23:28:22] INFO  WEBrick 1.3.1
[2015-03-26 23:28:22] INFO  ruby 2.1.5 (2014-11-13) [x86_64-linux]
== Someone is already performing on port 8080!

23:28:24 [rerun] Sinatra_with_reload Launch Failed
```

(note: adding rb-inotify to the gem file did not resolve this issue)

terminal window 2
```
username@ruby-newbie:~/workspace (master) $ lsof -wni
COMMAND     PID   USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
vfs-worke  9660 ubuntu   12u  IPv4 725746505      0t0  TCP 127.0.0.1:17123 (LISTEN)
ruby      13947 ubuntu    7u  IPv4 726206914      0t0  TCP *:http-alt (LISTEN)
```
manually terminating via kill -9 13947 is successful.

**Comment by ZachBeta** [comment]
Thanks so much for the detailed issue. I'll look into it soon :smile_cat:

**Comment by ZachBeta** [comment]
Looks like we can use http://www.sinatrarb.com/contrib/reloader instead.
This is now handled in 1b205f9770fd301695f9c0026f552a9d18f20424

I'll try to bulk make this change so that every project can auto-reload for a better experience across the board. Let's leave this issue open until that's done.

**Comment by LianaSaussy** [comment]
Great, thanks for looking into this! See you at the next meetup.

**Comment by ZachBeta** [comment]
everything should use reloaders now!
fa8504abcf0edc972e1a6b8b77d0848b734dec24
