### ISSUE TITLE
Need new ideas for micro ruby web apps

### ISSUE THREAD

**Issue by ZachBeta** [ZachBeta/ruby-newbie#7]
The `README` contains a handful of projects, but we need more so that people don't run out over the course of an event!

I like the idea of:
1. Explore a VERY basic concept in web programming
2. Small challenges and changes for people to explore deeper if they want

**Comment by ZachBeta** [comment]
I like the idea of doing a basic JSON api so people can send something and get something back. How they hit the running api may take some extra explaining but should be doable within ruby as well.

Also something to explain status codes, possibly a simple form with validation

**Comment by treznick** [comment]
The hobbes scripts might be a good place to start for very easy api ideas

**Comment by alexwilkinson** [comment]
Something with movies? Like a movie search micro app? People can use one of the keys I already have for a movie API and then I could just change my key.

**Comment by ZachBeta** [comment]
Suggestion from Casey:
> caseywatts [10:22 AM]
> I've used a "youtube playlist creator" app as an example pretty successfully!
> https://gist.github.com/caseywatts/399c7fccaf8214a3c7fa
> https://github.com/yale-stc-developer-curriculum/Yalies-On-Rails-2014-Spring/wiki/Week-5-6-Assignments

**Comment by ZachBeta** [comment]
@danbernier : text video game for a summer refreshment stand (burgers and fries and ice cream), program the game and people play it and take random orders

**Comment by ZachBeta** [comment]
@jhirbour : website redirector

**Comment by danbernier** [comment]
Here's the fry shack "game" I was talking about: https://github.com/danbernier/fry_shack

**Comment by ZachBeta** [comment]
@treznick hubot scripts:
pick one
random cat pics from http://edgecats.net
random gif from giphy

**Comment by alexwilkinson** [comment]
"Jukebox" app. You can "play" a song, get a list, etc. I did this at flatiron, I'll look it up and send it to you.

**Comment by jhirbour** [comment]
A url redirector/minifier using Sinatra. 

```
require 'sinatra'
set :bind, '0.0.0.0'

urls = {
  'jhirbour' => 'https://some_other_url'
}

get '/' do
  'Nothing to see here, just a url redirector'
end
get '/:user_id' do
   # erb :index
  if urls.has_key?(params['user_id'])
    redirect(urls[params['user_id']])
  else
    'no user found'
  end
end
```

**Comment by ZachBeta** [comment]
* Recipe API to figure out a potluck
* Text driven menu using thor
* Read CSV
* Create a ToDo list app
* Write a CSV
* "Mail merge"
* Unit converter
* Meme generator via API or via ImageMagick
* Build a markov chain (use a gem) chat bot (not a web app, just in REPL)
* Count words in a file
* Spell checker via a hash
* Make your computer talk!
* A form RSVP
* Make something that's actually DB backed (SQLite)
* Sending email
* Sending texts
* Tax calculator
* Interest rate calculator
* Bowling scorer
* Fill in a field with a comma separated list of people (musical chairs) that picks one
* Where should I go to lunch - hit yelp api, pick one
* Read latest issue from SeeClickFix in my neighborhood: query neighborhood, query issue
* tip calculator
* check splitter
* Pokemon api

**Comment by ZachBeta** [comment]
* Microblogging clone in memory

**Comment by ZachBeta** [comment]
* List some ingredients, have it pick a pizza or a sammich

**Comment by ZachBeta** [comment]
* Turtle render in an image? (Forward, Turn 90, Forward, Turn 90, Forward, Turn 90, Forward : square)

**Comment by jhirbour** [comment]
+1 for Turtle aka logo: https://github.com/andypike/kame

**Comment by ZachBeta** [comment]
https://github.com/benjaminoakes/pencil_mustache

**Comment by ZachBeta** [comment]
visitor count

**Comment by ZachBeta** [comment]
Going to mark this as closed and move these ideas into a "TODO.md"
